export const PRODUCTS = [
  { id:1,  name:"Products A", price:299,  desc:"Body text for whatever you'd like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.", sold:7  },
  { id:2,  name:"Products B", price:450,  desc:"Body text for whatever you'd like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.", sold:5  },
  { id:3,  name:"Products C", price:120,  desc:"Body text for whatever you'd like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.", sold:0  },
  { id:4,  name:"Products D", price:899,  desc:"Body text for whatever you'd like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.", sold:12 },
  { id:5,  name:"Products E", price:350,  desc:"Body text for whatever you'd like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.", sold:3  },
  { id:6,  name:"Products F", price:199,  desc:"Body text for whatever you'd like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.", sold:8  },
  { id:7,  name:"Products G", price:520,  desc:"Body text for whatever you'd like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.", sold:15 },
  { id:8,  name:"Products H", price:750,  desc:"Body text for whatever you'd like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.", sold:2  },
  { id:9,  name:"Products I", price:180,  desc:"Body text for whatever you'd like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.", sold:9  },
  { id:10, name:"Products J", price:1200, desc:"Body text for whatever you'd like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.", sold:4  },
  { id:11, name:"Products K", price:390,  desc:"Body text for whatever you'd like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.", sold:11 },
  { id:12, name:"Products L", price:650,  desc:"Body text for whatever you'd like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.", sold:6  },
  { id:13, name:"Products M", price:280,  desc:"Body text for whatever you'd like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.", sold:18 },
  { id:14, name:"Products N", price:430,  desc:"Body text for whatever you'd like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.", sold:1  },
  { id:15, name:"Products O", price:990,  desc:"Body text for whatever you'd like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.", sold:7  },
];
  export const USERS = [
    { id:1,  name:"User 1",  type:"Member" },
    { id:2,  name:"User 2",  type:"สมาชิกทั่วไป" },
    { id:3,  name:"User 3",  type:"สมาชิกทั่วไป" },
    { id:4,  name:"User 4",  type:"Member" },
    { id:5,  name:"User 5",  type:"Member" },
    { id:6,  name:"User 6",  type:"สมาชิกทั่วไป" },
    { id:7,  name:"User 7",  type:"สมาชิกทั่วไป" },
    { id:8,  name:"User 8",  type:"สมาชิกทั่วไป" },
    { id:9,  name:"User 9",  type:"Member" },
    { id:10, name:"User 10", type:"Member" },
    { id:11, name:"User 11", type:"สมาชิกทั่วไป" },
    { id:12, name:"User 12", type:"สมาชิกทั่วไป" },
  ];